version: "3"
services:
  bot: 
    build: bot-docker
    ports: 
      - 8000:8000
    networks:
      botfast:
        ipv4_address: 172.19.0.44
  fast:
    build: fast-api
    ports:
      - 80:80
    networks:
      botfast:
        ipv4_address: 172.19.0.45

networks:
  botfast:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24